### ISSUE TITLE
Printer prints at two positions

### ISSUE THREAD

**Issue by BeefEX** [Lunatrius/Schematica#170]
If I try to use printer, it prints at the correct position, but also one block lower. It happens in MC 1.10.2, with the last version on Schematica from Curse. Only tested on server.

**Comment by BeefEX** [comment]
BTW, the server is vanilla and there are no anti-cheat plugins. Same behaviour on Realm.

**Comment by Lunatrius** [comment]
Would be great if you could check this in SP as well. Might be the vanilla/Forge difference again, which might be a bit hard to fix.

Also, do you have the option for requiring adjacent blocks turned off or on?

**Comment by BeefEX** [comment]
Adjacent blocks is on, and now that I think of it, it worked when it was off.

**Comment by Lunatrius** [comment]
That's... weird. *Place Only Adjacent (placeAdjacent)* places blocks only if there is an adjacent block next to them when it's set to *true*.

Setting it to false allows you to build things that are not on the ground (air builds or when a schematic contains a lot of blocks that form a checkers pattern.

**Comment by BeefEX** [comment]
Sorry just noticed I wrote it wrong, it is off and works when it is on. :( My bad

**Comment by Lunatrius** [comment]
In that case it's the Forge vs vanilla [difference](https://github.com/MinecraftForge/MinecraftForge/blob/b380ba717fdfceeb204b6dd4d1e92a03f739ad5f/patches/minecraft/net/minecraft/block/Block.java.patch#L31-L35). There is not a lot that I can do to fix the issue, simply because I don't have the necessary information to place the blocks properly into the world.

```patch
     public boolean isReplaceable(IBlockAccess worldIn, BlockPos pos)
     {
-        return false;
+        return worldIn.getBlockState(pos).getMaterial().isReplaceable();
     }
```

For things like air and grass the above code change means that vanilla considers that block as a non-replaceable block, while Forge "fixes" this.

**Comment by BeefEX** [comment]
Thanks, I will just use adjacent block only than.

**Comment by BeefEX** [comment]
I just want to note that I dont think it has to do anything to do with block not being replacable. Printer does not work even like 50 blocks above. I will post screenshots of what happens tomorow.
