### ISSUE TITLE
Swapping blocks, how do I do it?

### ISSUE THREAD

**Issue by keem85** [Lunatrius/Schematica#194]
Hi there

I read two threads about a way to swap block type on the schematics. You said you implemented it as a command line, but I can't find out what the command is for switching from for example Oak to Spruce on a building.. I checked the config file also, but couldn't find any indication on how to swap them.. What is the command? 'm using 1.7.10.

Also, is it possible to use "Print" mode on my own server, without having to install Schematica.jar to my server's mod folder? I'd like to keep it clientside only.

**Comment by Lunatrius** [comment]
The command `/schematicaReplace` was added in 1.8 and can't be used in 1.7.10 or earlier versions.

It's not required on the server.

*Questions like this belong to the server thread.*

**Comment by keem85** [comment]
Ok, but how do I use it to replace oak with spruce for example?

**Comment by Lunatrius** [comment]
The basic syntax for the command is (also shown in-game):
```
/schematicaReplace <searchBlockState> <replacementBlockState>
```

A really simple example would be the following:
```
/schematicaReplace dirt grass    (or minecraft:dirt/minecraft:grass if you tab auto complete)
```
---
That is alright, but the state selectors are a lot more powerful. Both the search and replacement block states can use block state filters/states in square brackets. A really simple example that turns all blue glass into blue hardened clay:
```
/schematicaReplace glass[color=blue] hardened_clay
```

## Why and how does it work?

### searchBlockState
The state properties (stuff inside square brackets `[]`) are essentially a filter. If you don't specify any properties it will match ALL blocks of that type. If you list all properties it will match only those specific blocks. You can include as many of the properties for the block as you want.

A few examples
```
powered_repeater                                      -- matches ALL powered repeaters
powered_repeater[locked=true]                         -- matches only locked powered repeaters
powered_repeater[delay=1,locked=false,facing=north]   -- matches only unlocked powered repeaters with a delay of 1, facing north
```

### replacementBlockState
The state properties work in a similar way, but not quite. When a block is replaced the default block state is used as the base template for the new block.

What does this mean? In the previous glass example all blue glass way replaced by blue hardened clay. Why? Because the replace command tried to copy **all** properties over to the new block.

Any properties that are common for both blocks will be carried over. Some of the more common properties that are shared with multiple blocks are `axis`, `facing`, `colors`, `powered` etc.

Of course you can specify an override for the property in square brackets to override the default/copied property with something else entirely. Say, if you wanted to replace blue glass with yellow hardened clay, you're add `[color=yellow]` to the previous command:
```
/schematicaReplace glass[color=blue] hardened_clay[color=yellow]
```

**Comment by hi5kba** [comment]
i got a Question..  i want to stop Users using mods like this and WDL to copy my worlds.

for example: [eZProtector](https://www.spigotmc.org/resources/ezprotector.12663/)

i have a Problem however. that Targets everyone. 
we plan to routinely run build events and i don't want to have be around to disable our Protection every time judges want to export a area and i don't want grant server console to anyone else to do that either.

is there a specific way to make this possible?

if you could Drop me a PM or something about this that'd be a great help!

**Comment by Pokechu22** [comment]
I am the maintainer of WDL.  Read the documentation on [WDL's plugin messages](http://wiki.vg/Plugin_channels/World_downloader), and look into [my bukkit implementation](https://www.spigotmc.org/resources/world-downloader-api-wdlcompanion.19950/); the whole system is designed **specifically** for that use-case (disabling by default but allowing permission requests from players for cases where they actually need to download something because there _are_ valid cases for that).

I don't know the details of schematica's equivalent, but probably something similar exists -- though I don't think there's a built-in request screen.

**Comment by Lunatrius** [comment]
There is [SchematicaPlugin](https://www.spigotmc.org/resources/schematicaplugin.14411/), which uses the permission based system. No built in GUI, but it should be easy to control.

**Comment by Twi5TeD** [comment]
any reason why you cant replace signs? ive tried doing wall_sign and standing_sign which says replaced 0 the signs are placed on a chest but it wont let me remove them any help?

**Comment by Lunatrius** [comment]
They are tile entities, not simple blocks.

**Comment by Twi5TeD** [comment]
so its not possible to remove it from a schem?

**Comment by Lunatrius** [comment]
Not at the moment, it may be possible in the future.
