### ISSUE TITLE
Printer not working with double slabs

### ISSUE THREAD

**Issue by belph** [Lunatrius/Schematica#20]
I am running MC 1.6.2 (my server is making me), and the Schematica printer won't print any of the double stone slabs in my schematic. I saw this was an earlier issue, but it said it was resolved. It is still present on my copy of the mod, though.

**Comment by Arcrammer** [comment]
Hello, Lunatrius and Belph. I'd also like to mention that I'm facing the same issue. It's not a big deal until I work with a skyscraper 256 blocks tall because that means I'd have to place 512 slabs for each block they take. I'd also like to ask if you'd possibly be able to update this for 1.8 or 1.8.1 soon, and if there could be a way to easily place all blocks for the entire schematica at once rather than placing only three (it seems like five to me, but whatever) blocks around the users' character at a time. Thanks for reading!

**Comment by Lunatrius** [comment]
It's not that trivial of a thing to get working. I've been focusing on things that are a higher priority and this is one of the lower ones. Adding slab support to the current implementation would be nothing but hacks and I'd rather just plain out rewrite the entire thing instead of adding hacks and then avoid touching the code again.

The range limit on the printer is a vanilla limitation, nothing that I can affect with the printer itself.

As for 1.8. I've said before, I'm working on it. The entire rendering part of the mod has to be rewritten due to the model base changes in 1.8 and it's no easy task. I have to rip apart the entire vanilla rendering in order to figure out how exactly things work.

Oh and I'll be removing the FMP tag. Given my recent attempt to *try* to get the multiparts to render failed I don't see this be a thing for a while.

**Comment by Zarbuz** [comment]
Up!
I think the mod is well advanced for the 1.8 for this "small" bug is corrected :)
I admit I have a structure that contains many double slabs ^^
In any case, congratulations for this mod! I find it really useful!

**Comment by Lunatrius** [comment]
By no means is this considered a small/easy thing to patch up. I have implemented a temporary solution in d95c0433ee8e2102f09d330cee81c2083f3281a3 and will hopefully improve it over time. It triggers "right click" twice instead of just once. I imagine that this won't work too well on servers.
