### ISSUE TITLE
Question: What's the difference between the "Alpha (standard)" and "structure block" formats? 

### ISSUE THREAD

**Issue by tspierer2** [Lunatrius/Schematica#282]

**Comment by Pokechu22** [comment]
The difference only matters when you use the saved schematics outside of schematica.

* "Alpha (standard)" produces a [.schematic file](https://minecraft.gamepedia.com/Schematic_file_format) which can be used in external programs such as MC-Edit.  It's called alpha because it uses the normal Minecraft material list (which internally is called "alpha", where the other options are "classic" and "pocket"); this format can be used in external programs such as MC-Edit.
* "Structure block" produces a [.nbt structure file](https://minecraft.gamepedia.com/Structure_block_file_format) which can be used in Minecraft itself via structure blocks, even without schematica installed (this will be more useful in the future since you can use them for generated structures)

Within the mod there is no significant difference between the two.

**Comment by Lunatrius** [comment]
Pokechu22 pretty much explained the difference between the formats.

*A note: there are some limitations when importing a structure format schematic using the vanilla import mechanism, namely nothing larger than 32x32x32. You can save bigger schematics, but the importer will trim anything above those dimensions.*
