### ISSUE TITLE
SchematicaReplace command replaces other blocks

### ISSUE THREAD

**Issue by Quetip** [Lunatrius/Schematica#300]
I use the schematicaReplace command for stone to hardened clay (/schematica Replace stone hardened_clay) but the command also replaces other blocks: granite, diorite, and andesite. I don't know if this is intended or issue has been posted before if so apologies.

**Comment by Pokechu22** [comment]
Stone, granite, diorite, and andesite are all (currently) the same block, using different states to differentiate themselves (look at them in F3 and you'll see this on the right hand side).  You thus need to specify exactly which state you want to change, in this case via `/schematicaReplace stone[variant=stone] hardened_clay`.

Note that in 1.13, as part of [the flattening](https://minecraft.gamepedia.com/1.13/Flattening), these will be separated into real different blocks, so that will no longer be necessary.

**Comment by Quetip** [comment]
Ah ok.
