### ISSUE TITLE
[Suggestions] Placing block values, move bot, summary notification, toggle-able overlay 

### ISSUE THREAD

**Issue by smcclennon** [Lunatrius/Schematica#341]
I think It would be super useful, for example, the printer to be placing a repeater that needed to be at a four tick delay, to right click the repeater until it met that delay. Or a noteblock that needed to be a certain pitch, to set it to that pitch. If schematics have limitations with the noteblock pitch, perhaps add a "save as RICH schematic" so that it does remember pitch.

When in creative mode, with super huge builds, It can get very tedious flying around. It would be really cool if you could add a feature where it moves the player (as smoothly as possible, configurable so that you can get around some server anticheat) so it can place the blocks.

I would love a summary feature where if you hit a button on a menu, It tells you how many blocks have been placed/destroyed, how many need to be placed, blocks with incorrect values (such as a repeater set to one tick when It needs to be 2) and an option to highlight blocks with incorrect values (and/or) blocks that need to be placed / destroyed.

And finally, I find it really annoying sometimes with big schematics, I can't see the actual build. I would like a button to toggle the "holographic" overlay.

**Comment by Lunatrius** [comment]
Printer adjusting blocks like repeaters is a feature that I want to add to the mod, but it will require quite some refactoring of the existing code (as if there wasn't enough already).

Note blocks won't work in the current version, because the client has no way of knowing the pitch without actually changing it, and even then it's tricky.

Auto walk is a no. I don't have the time and will to code an AI that will move around while placing blocks. The mod is supposed to be a helper utility, not a bot. I have considered to take out the printer, but I've left it in the mod, for now.

The summary should already be on the materials menu. It lists the amount of placed and required blocks. It does not currently list incorrect blocks.

Do you mean a hot key to turn ti on and off? Go into the options and assign a hotkey, it's not assigned by default.

**Comment by Shiraz2014** [comment]
Please do not ever remove the printer.
