### ISSUE TITLE
what are the variants for stone brick in /schematicaReplace

### ISSUE THREAD

**Issue by Instinctual777** [Lunatrius/Schematica#437]
i want to replace all the mossy, chiseled and cracked stone brick in a schematic with normal stone brick, but there's no listing of what property to use.
i've tried variant=mossy, variant=mossy_brick, using normal minecraft ids, and basically everything else i could think of. none of it works.

is there anywhere i can get a list of the variants for stone bricks? doesn't really make much sense to have proprietary block variants without having any documentation or listing of them.

**Comment by Pokechu22** [comment]
It should be the ones just directly visible on F3 as used in normal minecraft (look on the right side and you should see `minecraft:stone_bricks` and then `variant=mossy` (as far as I can tell).  Unfortunately these IDs changed in 1.13+ due to the flattening so there's less documentation about them nowadays, but they _are_ the normal ones as they appeared in 1.12.

I _think_ that you can also just not specify variant and it'll ignore the variant for the purpose of replacing - something like `/schematicaReplace stone_bricks stone_bricks` or `/schematicaReplace stone_bricks stone_bricks[variant=normal]`.

**Comment by Instinctual777** [comment]
yeah the f3 thing worked, thanks
