### ISSUE TITLE
Unable to replace DarkOak plank variant

### ISSUE THREAD

**Issue by Finn0001** [Lunatrius/Schematica#479]
Hello,
I'm unable to replace variant of Dark Oak. Everything else seems to replace just fine. Is the Dark Oak variant in the code? It would also be nice if we could just use IDs instead of words. Such as 5:5

Thanks!

**Comment by Finn0001** [comment]
Or a GUI option. Click on the block and a drop down appears etc

**Comment by Finn0001** [comment]
/schematicareplace minecraft:planks[varient=birch] minecraft:planks[varient=dark_oak]
"varient=birch" is not a valid property for "minecraft:planks"
....
Is there a master list we could look at for the blocks and their varients

**Comment by Pokechu22** [comment]
[Burger](https://pokechu22.github.io/Burger/1.12.2.html#blocks:planks) has a list (though it won't be entirely consistent with the values you use ingame due to the way that list is generated; in general it should just be changing `ALL_CAPS` to `lower_case`).  I think you can also tab-complete the names?  In this case, the problem is that `variant` has an a, not an e.

**Comment by Finn0001** [comment]
Hey! Thanks for your response. I just realized I spelled the command incorrectly lol
This list is awesome! Thanks much
