### ISSUE TITLE
API for hooking into the Schematic Saving process.

### ISSUE THREAD

**Issue by AtomicBlom** [Lunatrius/Schematica#68]
> [current progress](https://github.com/AtomicBlom/Schematica/compare/apiv2) -- Lunatrius

I need to be able to manipulate a schematic at two points during the saving process.

Once the SchematicWorld has been generated, I need to manipulate the blocks that have been gathered (in my case specifically, I'm going to convert External Air to a null block, and Internal Air, and Air Marker Blocks to normal Air)

Once that is done, the normal save process can proceed, but I'll need another event to manipulate the block mappings to remove references to my mod, and to insert additional metadata into the schematic.

I have a pull request @Lunatrius and I have been commenting on in twitter, but we need a better place to discuss it.

**Comment by AtomicBlom** [comment]
If anybody else wants to jump into this dicussion, the proposed API is being developed here:
https://github.com/AtomicBlom/Schematica/tree/apiv2/src/api/java/com/github/lunatrius/schematica/api

and if you need to know why it is I'd like it, please refer to this youtube video:
https://www.youtube.com/watch?v=9SvwyCJCGjU&t=2m36s

**Comment by Lunatrius** [comment]
Could've just created a PR instead of an issue (could track progress, kinda). Anyway, let's get to the better part!

The `asWorld` method shouldn't be needed. What I had in mind was a separate class for the underlying data. The current SchematicWorld would only serve as a proxy between the data container and the renderer/printer. Because of that, the "ISchematic" container would have both, get and set methods.

**Comment by Lunatrius** [comment]
Or alternative link: https://github.com/AtomicBlom/Schematica/compare/apiv2

**Comment by AtomicBlom** [comment]
There's a few things that are coming out of that branch. I was originally going to offer myself access to the raw NBT data (which was the reason for moving the Names.NBT) but that's an easy way to shoot yourself in the foot manipulating everything by hand so I won't end up doing that.

Instead I'll expose the mappings in the PreSchematicSaveEvent, together with an NBTTagCompound that you can store arbitrary additional information into. I'm unsure on where to put it in the NBT tree, I'm thinking /SchematicMetadata or something

**Comment by AtomicBlom** [comment]
asWorld has been removed, if Schematica moves towards a data class independent of the renderer/printer then it almost certainly won't be needed.

I had already exposed a few of World's methods in the interface which make up the basic behaviour I need:
* getBlockId
* getBlock
* setBlock
* getTileEntity
* getTileEntities
* setTileEntity
* removeTileEntity
* getWidth
* getHeight
* getLength
* blockExists - might not need this one

**Comment by Lunatrius** [comment]
`getBlockId` shouldn't be needed, at least not in the interface. Adding `getMetadata`/`setMetadata` would be a good thing. Don't think that `blockExists` will be needed, `getBlock` will return air for anything outside the schematic anyway.

There should be no other data available in the schematic anyway, from what I can tell. Blocks(+meta/TE) and the dimensions.

**Comment by Lunatrius** [comment]
Having `getIcon` in the interface would be good to have in the interface as well. That should allow the current write method in `SchematicFormat` to take the interface as a parameter instead of the implementing class.

**Comment by AtomicBlom** [comment]
I think I'm done making changes to the API. I'm just going to try using it in Schematic Meta-Blocks before I squash and PR it. I've included all your feedback.

**Comment by Lunatrius** [comment]
About the mappings. I don't feel too comfortable allowing people to manually tweak those. The only purpose of the mappings is to be able to use schematics across multiple worlds. It doesn't appear that you actually use the event mappings anyway. It may result in invalid metadata and/or tile entities.

Will add some other stuff later, am in a bit of a hurry.

**Comment by Lunatrius** [comment]
Just noticed that the mappings are just passed on in the event. Is there a reason why somebody may be interested in them?

Other than that, think it should be fine. Only thing before the actual PR would be to strip `ISchematic` off and comment out the event firing lines with `// TODO:`. I'll then implement the interface on the class containing the data only.

**Comment by AtomicBlom** [comment]
I'm using the mappings it to remove references to Schematic Meta Blocks from the schematic. After my post-processing, there is a single block left called schematicmetablocks:NullBlock, which I'm changing it's block identifier to null. (I don't want to tie down the implementation of handling null blocks to my mod.)

**Comment by Lunatrius** [comment]
So, all the "air" blocks are converted to a single "air" block (NullBlock)? I can definitely see the use case in that. But exposing the raw mappings doesn't sound like a good idea. Not only because things may go wrong but also because the mapping itself, as I already said, is raw data.

Instead of going the current route, how about mappings that override the blocks before anything is processed? Sure, it will use *some* extra time processing everything, but at least it shouldn't break anything.

As for the implementation itself. A small utility class containing the block and metadata (BlockData? BlockState?) should get the job done. In 1.8 that can be removed in favor of block states.

The event itself can be fired right after the dimensions are set ([#](https://github.com/AtomicBlom/Schematica/compare/apiv2#diff-97f4ced3cf32f04f98a45c96909662adR105)), but the body of the loops below has to be tweaked slightly. Have to get the Block and metadata from the schematic. If the mappings contain anything remap accordingly, then grab the block ID from the registry. The rest should be the same.

**Comment by Lunatrius** [comment]
Oh and one more thing. All unknown blocks (blocks from mods not present when loading the schematic) will be "remapped" to air right now.

**Comment by Lunatrius** [comment]
Would it be worth putting the events into an `events` sub package? Just a random thought.

**Comment by AtomicBlom** [comment]
the NullBlock shouldn't be converted to air in my case. It's a placeholder that literally means "do nothing at all at this spot when loading the schematic." The interior air blocks (Implicit Air, Explicit Air, Internal Air Marker) all get turned into vanilla air blocks.

I think your current behaviour of converting unknown blocks into air is entirely appropriate for Schematica, but rather something I'll handle in a customized schematic loader in SteamNSteel that has an event handler for unknown block types. The idea being that the handler can either cancel the setBlock (and leave the current terrain intact) or perhaps swap it out, or in some cases, Execute code.

An example of this last case is a metadata block with associated tile entity that represents " Extend the block above downwards until it reaches the ground, thereby creating pillars that could hold up a building.

The logic for that would sit inside SteamNSteel, but I want the metadata to be there, even though it probably isn't valid for a normal schematic loader.

**Comment by AtomicBlom** [comment]
events sub package? Absolutely, I can do that.

**Comment by AtomicBlom** [comment]
Here's an example Integration example that exercises a fair whack of the API.

https://github.com/AtomicBlom/SchematicMetaBlocks/blob/master/src/main/java/net/binaryvibrance/schematicmetablocks/SchematicSaveListener.java

**Comment by Lunatrius** [comment]
Oh, right. Forgot that you actually have the loading part directly copied and modified over. Silly me.

At this point (after doing the things mentioned earlier) everything should be good to go. You can also revert all the changed to SchematicWorld, the data stuff will be extracted anyway.

**Comment by Lunatrius** [comment]
Here's an idea. Since you're passing a reference of the map into the event, the "local" mappings are modified anyway. Instead of directly exposing the mappings people could tweak the names via methods, which would result in less code on your end.
```java
public boolean replaceMapping(String oldName, String newName) {
    Short id = this.mappings.get(oldName);
    if (id != null) {
        this.mappings.put(newName, id);
        return true;
    }

    return false;
}
```
Though, there is still the issue of what to do if there are duplicate names? A really simple example is replacing stone with wool, where wool already exists. Remapping the stone to wool would end up overriding the already existing mapping. That will cause all wool blocks to be left without a mapping name.

**Comment by AtomicBlom** [comment]
Yeah, certainly my original desire was to replace the blocks in mapping, rather than using setBlock, certainly my goal is to map air to null, then map three block types to air.

In practice I'm not sure that's possible or even safe. I love the idea of having a replaceMapping as it would protect consumers from doing stupid things. I would error if there is a collision in the mapping however, and in the exception, warn them they should be replacing blocks in the PostSchematicCapturedEvent if they wish to work around the collision.

**Comment by Lunatrius** [comment]
Not a bad idea. Throwing something along the line of `DuplicateMappingException`/`MappingCollisionException` would certainly prevent most issues.

Actually... yeah. The remapping can be done in the capture event if desired. It may not be easy, but at least it offers "full" control of what and where to replace.

Might want to add a setBlock method to the interface without the metadata, which can be implemented to shortcircuit into the other method with metadata 0 later on.

**Comment by AtomicBlom** [comment]
I've added that setBlock without metadata, the exception, and took the time to add a heap of documentation to the api classes/interfaces.

I'm feeling pretty good about it about now. I'll test it all out with my mod again tomorrow and PR after that if there are no further requests.

**Comment by Lunatrius** [comment]
Okay, that's some detailed JavaDoc. :D

Don't think that I have anything else to add myself. `extendedMetadata` could possibly be a public final field instead of being private and having a getter and the exception message could be shorter. First line should be sufficient, the rest is stated in the documentation already.

**Comment by AtomicBlom** [comment]
https://github.com/Lunatrius/Schematica/pull/69

**Comment by Lunatrius** [comment]
Didn't notice it earlier, but I'll just expose the schematic property in `PostSchematicCaptureEvent`.
