### ISSUE TITLE
there seems to be alot of rendering issues now?

### ISSUE THREAD

**Issue by intangir** [Lunatrius/Schematica#74]
is it 1.8 related?
i notice it seems to overlay the transparency even if the block is already in the right spot, flickers alot

also the red/orange/purple tinting doesn't work on wrong blocks at the moment?

**Comment by Lunatrius** [comment]
It's a beta at best right now, because people would pitchfork me if they had to wait for the proper release.

The blocks are currently *not* checked against the real world and are always rendered. The flickering is just regular z-fighting because 2 textures are displayed on the same location.

Correct, I still have to code the highlighting code.

**Comment by intangir** [comment]
did you have to redo alot of the code with 1.8?

i also noticed rotation is not available at the moment

its a bummer it takes so much work to convert it but i really appreciate this mod, it is so handy

**Comment by Lunatrius** [comment]
Almost the entire rendering code (apart from the shader class) was removed/replaced. Trying to workout the overlays to function similarly to how vanilla works.
