### ISSUE TITLE
Allow selecting multiple layers in the printer

### ISSUE THREAD

**Issue by lucom** [Lunatrius/Schematica#81]
Currently one can only select a single layer to print / display.

It would be great to be able to select the amount of layers to display, e.g. layer 2 - 4.

Alternatively: Select the box of blocks to display / print, e.g. 1;0;4 to 2;2;4

**Comment by Lunatrius** [comment]
Selectable amount of layers shown is an option. I'd most likely toss that into the config file because it will rarely change (and can be changed from in-game as well, requires a few extra clicks tho).

The alternative is out of the question for now. That would require maintaining a list/array of selected layers/bounding boxes and it wouldn't be the easiest thing to use for the end user.

**Comment by Lunatrius** [comment]
The layer selection and toggling hotkeys should be good enough for this. The feature affects everything related to the schematic (renderer, printer) and a decent chunk of things would have to be special cased to make sure things don't explode when the layer count is higher than the schematic itself.
