### ISSUE TITLE
Suggestions: handling of 1.8.x stuff in 1.7.10 - and some findings

### ISSUE THREAD

**Issue by MoonCutter2B** [Lunatrius/Schematica#90]
a) Thanks for fixing the tall grass stuff in 1.7.10 - works. nicely.
b) current printing problems (?) in 1.7.10: sometimes the follwing items cannot be printed: anvils, monster heads, and most common double halfslabs. Note that the schematic is from 1.8.8 that I try to print in 1.7.10 so that might be the reason.
c) I would love to get a warning/info that the schematic contian items that doens't exist in the MC version I'm using, like fences of other types of wood. Even better possiblility to replace them with something else.
d) The materials info is very useful, but is it possible to also calculate/present both the total needed and the remaining needed? Like "cooblestone 7 of 34" i.e. 27 is already corretly placed.

**Comment by Lunatrius** [comment]
Anvils shouldn't have any problems, unless it has issues picking up the correct type of anvil. Also, player orientation matters. Same thing applies to skulls.

Due to the changes made in the latest version double slabs most likely won't work anymore. The picked item is no longer a double slab, but a single slab, which is why it has issues placing them.

That is impossible. Schematics made in newer versions should not be used in older versions of the game. 1.8 has converted the internal representation of items from the ID to the unique name, which will fail to be read in 1.7.10. Traversing the NBT tree manually trying to convert the IDs back is impossible to do without a strictly defined structure. Something might looks like an item stack in NBT, but represents something entirely different.

The *recent* update to the material list was sort of a preparation for this, but I have to work out a few implementation details before it can be added.

**Comment by MoonCutter2B** [comment]
ok, thanks.
Regarding c) was was thinking more of a manually thing, not something automatic. Or maybe even just a ghost image in a new color. I  know a lot of stuff has changed so. Problem for me was that there was no info that the schematic was from 1.8.x.

**Comment by Lunatrius** [comment]
I may have to talk to the other people supporting the mcedit format to see if we can get a universal tag added to newly created schematics that includes the tool used that saved it and the Minecraft version that it is meant for.

**Comment by Lunatrius** [comment]
The blocks placed / blocks required thing was added with 936d4f25033fc9962a5b8456db169648e7004f6e.

**Comment by MoonCutter2B** [comment]
Hi!

Excellent, thank you !

/MoonCutter

**Comment by Lunatrius** [comment]
Won't bother adding the tool tag. I've tried to push a few tweaks for the schematic format a few times, but nothing was ever done/even considered. At this point I can either start using my own format (not exactly user friendly, but would allow for extra stuff) or I keep the "legacy" mcedit format which is highly unlikely to receive any improvements.
