### ISSUE TITLE
[Crash]Aether2 and Schematica

### ISSUE THREAD

**Issue by zHawky** [Lunatrius/Schematica#96]
Well seems like they dont want working together..
Here a crashlog http://pastebin.com/JB6t9XTE

**Comment by Lunatrius** [comment]
This was an incompatibility with Gilded Games Utility that was fixed with gildedgames/gilded-games-util#15.

I'm not entirely sure whether it was already backported and released for 1.7.10. The latest version on CurseForge is from April, so unless it's being hosted elsewhere the fix was not backported/released yet.

**Comment by Collin1971** [comment]
Apologies for not getting the fix back-ported into our 1.7 branch sooner, was (rather extreme) forgetfulness on my part. I've compiled version 1.7.10-1.8 of Gilded Games Util and uploaded it [here](http://files.aetherii.com/files/versions/1.7.10-1.5.2/gilded-games-util-1.7.10-1.8.jar). We'll push the update to our other platforms as soon as possible.

**Comment by Lunatrius** [comment]
Awesome! Didn't realize that `1.7iochanges` was the actual branch for 1.7, could've submitted a PR for it if I knew that. I just assumed it was some left over branch that wasn't deleted.

**Comment by zHawky** [comment]
So what is that mean?

**Comment by Lunatrius** [comment]
Download and replace the previous version of the mod with the one @Collin1971 posted above.

**Comment by zHawky** [comment]
Ohh, sorry im so blind :P  
then going check it..
